### PR TITLE
Location encoder

### PR DESCRIPTION
**Pull request by tingaloo**
Just working on what Andy started [#14](https://github.com/codefordc/districthousing/pull/328)

Using [Google Geoencoder](https://developers.google.com/maps/documentation/geocoding/intro) to parse locations into latitude and longitude.

Limitations:
1. 2500 requests per 24 hour period.
2. 5 requests per second.

Location tables now <b>display</b> modal display button
Location tables now read from <b>locations</b> instead of <b>long and lat</b>.
Location modal now displays popup with name and address

Suggestions: 

Use Google Maps instead of OpenStreetMaps for cleaner maps.
A master map on housing index page to display ALL possible locations?

It really depends on the clients and the workers, but I am open for UX ideas.
Here is what I am thinking.

image

### CODE REVIEW

**Comment by tingaloo** [comment]
Slight bug on load.
Pop up skews to the right.
Closing and opening again fixes it. Not sure what's causing it.

image

**Comment by jrunningen** [comment]
Thanks!  It'll be nice to finally have mapped locations without having to expose the user directly to lat/long coordinates.

A single map showing all housing locations would be cool.  Feel free to implement that if you like.

I see an area for possible improvement.  Google's API docs say:

"Geocoding is a time and resource intensive task. Whenever possible, pre-geocode known addresses (using the Geocoding API described here or another geocoding service), and store your results in a temporary cache of your own design."

I recommend we do this, to minimize risk of hitting the API rate limits, and to be a good citizen.  We ought to check whether our PDFs have their lat and long attributes already set to something.  If so, use those, and don't make a Google API request.  If lat and long are blank, but the location attribute is set, then making a geocoding API call, and store the result in the lat/long attributes so we don't need to request the same address again.

**Comment by tingaloo** [comment]
I am not familiar with pre-caching best practices, is it as simple as how you described it?

**Comment by jrunningen** [comment]
Pretty simple.  All it means is that we should save the coordinates the first time we call the geocoding API for that address, so we don't need to make the same API call again every time we render the housing form.  Since it will require writing our own database, this'll have to be done in the HousingForm controller, rather than in the Javascript frontend.  Can you make the API call from Ruby?

**Comment by tingaloo** [comment]
I'll give it a twirl.

**Pull request merged**
