### PR TITLE
Datatables

### PR DESCRIPTION
**Pull request by mlouie**
This adds jQuery DataTables to our applicant list.  It focuses user input immediately on a search box to allow a case worker to begin searching for a client in the list.  This implementation will work for now, but we may need to hook this up to the backend if the number of clients gets too large for the browser.  Fortunately, there's supposed to be support for tying DataTables to a backend.

@jrunningen @jasoncorum Let me know if you guys have any qualms or tips to improve.

### CODE REVIEW

**Comment by mlouie** [comment]
Here's what the applicant list looks with the new data table.

screen shot 2015-01-17 at 5 05 42 pm

**Comment by jasoncorum** [comment]
I just took a quick look and had one question. Should the jQuery DataTables assets go in the vendor assets folders? What do you think @jrunningen?

I'll try to take a closer look tomorrow and also get on another issue.

**Comment by jrunningen** [comment]
:elephant:

**Comment by jrunningen** [comment]
@jasoncorum I agree, that should probably go in the vendor assets folder.  Go ahead and make that change if you feel up to it.

**Pull request merged**
